AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  WasteDisposalAwsLambda

  Sample SAM Template for WasteDisposalAwsLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  WasteDisposalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: WasteDisposalFunction
      Handler: handler.WasteDisposalRequestHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        WasteDisposal:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /disposal
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WasteDisposalApi:
    Description: "API Gateway endpoint URL for Prod stage for Waste Disposal function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/disposal/"
  WasteDisposalFunction:
    Description: "Waste Disposal Lambda Function ARN"
    Value: !GetAtt WasteDisposalFunction.Arn
  WasteDisposalFunctionIamRole:
    Description: "Implicit IAM Role created for Waste Disposal function"
    Value: !GetAtt WasteDisposalFunctionRole.Arn
